### ISSUE TITLE
Support multi-threaded atomics on Kotlin/Native

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.atomicfu#11]
Kotlin/Native implementation should be rewritten on top of native-specific `konan.worker.AtomicReference` class so that atomicfu-based code can be compiled into multi-threaded Kotlin/Native code.

**Comment by IgorKey** [comment]
Up.
Hi, @elizarov. Are there any updates?

**Comment by elizarov** [comment]
It is available in a branch `native-mt`
