### ISSUE TITLE
0.14.x missing from maven central

### ISSUE THREAD

**Issue by benasher44** [Kotlin/kotlinx.atomicfu#115]
Hello! I initially couldn't figure out why I couldn't resolve the latest coroutines version of atomicfu in my project, and then I realized it was because I was only pointing at `mavenCentral()` in my dependencies list. Re-adding `jcenter()` fixed it, but it'd be great to see atomicfu back up on `mavenCentral()`.

**Comment by qwwdfsad** [comment]
Synced version 0.14.1 to Maven Central. Thanks for pointing it out!

**Comment by benasher44** [comment]
🎉 awesome thanks for fixing!
