### ISSUE TITLE
Compile warning: "compileOnly dependecy is used in the Kotlin/Native target

### ISSUE THREAD

**Issue by patjackson52** [Kotlin/kotlinx.atomicfu#141]
When applying the atomic-fu gradle plugin to a multiplatform project I get the following in compiler output:

```
A compileOnly dependency is used in the Kotlin/Native target 'ios':
Compilation: main
Dependencies:
org.jetbrains.kotlinx:atomicfu-common:0.14.3
Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to 'implementation' or 'api'.
```

v0.14.2 & v0.14.3

**Comment by elizarov** [comment]
Thanks for the report. It is a known issue that will be fixed in future versions of Kotlin Gradle plugin. You can safely ignore it.

**Comment by qwwdfsad** [comment]
This is https://youtrack.jetbrains.com/issue/KT-32476.
On builds later than `1.4.0-dev-8958` you can use `kotlin.native.ignoreIncorrectDependencies=true ` to mute this warning

**Comment by colintheshots** [comment]
I have the warning in my gradle.properties and yet it gets ignored. I get to see the warning once for each module that uses a dependency that uses atomicfu.
