### ISSUE TITLE
Could not find org.jetbrains.kotlinx:atomicfu-native:0.14.4

### ISSUE THREAD

**Issue by william-reed** [Kotlin/kotlinx.atomicfu#158]
`0.14.4` is unable to resolve for native. `0.14.3` seems to work ok though.

```
implementation("org.jetbrains.kotlinx:atomicfu-native:${Versions.Libs.ATOMIC_FU}")
```

I only need this dependency in an iOS source set for a multiplatform project so I am adding the native dependency directly (for the appropriate source set). The `README` is not clear about this, but it seems reasonable that this should work

**Comment by SokolovaMaria** [comment]
You can either apply `kotlinx-atomicfu` plugin that will add native `implementation` dependency automatically or add it like this:

`implementation("org.jetbrains.kotlinx:atomicfu-${native-target}:${Versions.Libs.ATOMIC_FU}")`

The following native targets are supported: `linuxX64, iosArm32, macosX64, mingwX64, tvosArm64, tvosX64, watchosArm32, watchosArm64, watchosX86`
