### ISSUE TITLE
Gradle plugin: detect Kotlin platform and automatically add dependencies 

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.atomicfu#16]
Currently readme on Gradle says that you need to add the following dependencies to your gradle file:

```
dependencies {
    compileOnly "org.jetbrains.kotlinx:atomicfu:$atomicfu_version"
    testRuntime "org.jetbrains.kotlinx:atomicfu:$atomicfu_version"
}
```

This should not be needed. Plugin shall do it automatically on JVM. Moreover, plugin shall automatically detect what Kotlin platform is used (based on the Kotlin plugin that is applied) and also add appropriate dependencies for Kotlin/JS and Kotlin/Native.

**Comment by SokolovaMaria** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plugin](https://trello.com/c/gFakJqEW/26-plugin)
