### ISSUE TITLE
[BUG] `NoSuchMethodError` thrown if `AtomicInt` is used in constructor

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.atomicfu#166]
```kotlin
class A(val atomic:AtomicInt=atomic(0))
fun main()=println(A())
```
1) `Exception in thread "main" java.lang.NoSuchMethodError: A.<init>(Lkotlinx/atomicfu/AtomicInt;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
`
2) using `A(atomic(0))` won't compile, this should be a special case and compile

kotlin-gradle-plugin:1.4.0
atomicfu-gradle-plugin:0.14.3

**Comment by SokolovaMaria** [comment]
Passing references to atomic variables as parameters is not supported. You should declare the atomic variable as a field, like this:
```
class A(val v: Int = 5) {
    val a = atomic(v)
}
fun main() = println(A())
```
