### ISSUE TITLE
Non-atomic operation Under the coroutine

### ISSUE THREAD

**Issue by z589533** [Kotlin/kotlinx.atomicfu#18]
![image](https://user-images.githubusercontent.com/12063612/44130672-3231e546-a081-11e8-90c3-9bbf8307e059.png)
fun main(args: Array<String>) {
    val count = atomic(0)
    for (i in 0..100) {
        launch {
            count.incrementAndGet()
            println("out====$count")
        }
    }
    Thread.sleep(2000)
}
![image](https://user-images.githubusercontent.com/12063612/44130681-42a0f656-a081-11e8-9bcb-03a88a81648a.png)

**Comment by z589533** [comment]
atomicfu.version=0.11.1
kotlin.version=1.2.60
kotlin.coroutines.version=0.24.0

**Comment by elizarov** [comment]
What id you expect to get? Maybe you wanted to write something like this?

```
println("out====${count.incrementAndGet()}")
```
