### ISSUE TITLE
new gradle `plugin` grammar support

### ISSUE THREAD

**Issue by revintec** [Kotlin/kotlinx.atomicfu#200]
can we use the following new grammar inside `build.gradle.kts`?
https://docs.gradle.org/current/userguide/plugins.html#sec:binary_plugins

```
plugins{
    kotlin("atomicfu")version "xxx"
}
```

**Comment by mvicsokolova** [comment]
You will be able to apply the plugin using the `plugins` section like this:
```

```

**Comment by mvicsokolova** [comment]
You will be able to apply the plugin using `plugins` section, like this:
```
plugins {
 id("kotlinx-atomicfu") version "0.16.3"
}
``` 
when Atomicfu gradle plugin is published to the Gradle Plugin Portal. #56
