### ISSUE TITLE
Configuration cache problem when applying kotlinx-atomicfu Gradle plugin along with kotlin-multiplatform

### ISSUE THREAD

**Issue by ALikhachev** [Kotlin/kotlinx.atomicfu#212]
Original issue: https://youtrack.jetbrains.com/issue/KT-49165

There's a [configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) problem in kotlin-multiplatform test compilation task configuration: https://github.com/Kotlin/kotlinx.atomicfu/blob/1c9f04c3d584e2e6d8ceab133abb8b19d3c0ff51/atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt#L217
`compilation` object shouldn't be referenced from task action (the lambda passed into `doFirst`). It causes `compilation` object to be captured into the lambda and Gradle tries to serialize it.

Reproducer project: [KT-49165.zip](https://github.com/Kotlin/kotlinx.atomicfu/files/7596349/KT-49165.zip)

Configuration cache report: [configuration-cache-report.html.zip](https://github.com/Kotlin/kotlinx.atomicfu/files/7596359/configuration-cache-report.html.zip)

**Comment by e5l** [comment]
We have this problem in Ktor as well. You also could try using Provider API instead

**Comment by e5l** [comment]
It would be really great to fix this problem, cause it adds about 5 seconds for every single grade task we run in Ktor
