### ISSUE TITLE
Incorrect dependency for KMP common module "atomicfu-common"

### ISSUE THREAD

**Issue by ultraon** [Kotlin/kotlinx.atomicfu#214]
I've noticed that there is an incorrect dependency written on the main page of this repo.
```
dependencies {
    compile "org.jetbrains.kotlinx:atomicfu-common:$atomicfu_version" // <-------- "atomicfu-common" is incorrect
}
```
`atomicfu-common` isn't resolved.

So, it should be:
```
dependencies {
    compile "org.jetbrains.kotlinx:atomicfu:$atomicfu_version"
}

```

**Comment by chanakin** [comment]
Would someone please approve the poll request that mentions this issue? This took me hours to find so I could resolve the conflict with kotlinx-atomicfu and the kotlin-android plugin.
