### ISSUE TITLE
Kotlin Runner stops working in IDEA when adding a gradle plug-in AtomicFU

### ISSUE THREAD

**Issue by BorzdeG** [Kotlin/kotlinx.atomicfu#27]
If you enable the plugin AtomicFU, it ceases to run kotlin-runner in IDEA:

`Error: Could not find or load main class demo.AppKt`

demo project: https://github.com/bug-samples/kotlinx.atomicfu-27

**Comment by SokolovaMaria** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plugin](https://trello.com/c/gFakJqEW/26-plugin)

**Comment by BorzdeG** [comment]
@SokolovaMaria "Card not found."

**Comment by amal** [comment]
Same bug

```
kotlin 1.3.71
kotlinx.atomicfu 0.14.3
IDEA 2019.3.4
```
