### ISSUE TITLE
Add boxed atomics

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.atomicfu#407]
I am new to this library, and right away I am confronted with unique compiler errors if I try to use `atomic` in an un-sanctioned way. It needs to be in a constructor or class initialization.

To get around this, I create a wrapper for myself:

```kotlin
class BoxedAtomicInt(
    value: Int
) {
    private val value = atomic(value)
    fun getAndIncrement() = value.getAndIncrement()
}
```

This is a suggestion to add classes such as `BoxedAtomicInt` directly into the atomicfu library itself. 

As a newbie here, I am sure this is been brought up already. But searching through the issues and README, I couldn't find a discussion.

I understand that boxing has a performance cost. However, it seems unboxed `atomic` introduces novel restrictions on the compiler level that reduces the flexibility of their usage. If all of these restrictions are all in the name of a performance boost, I am not sure this is justified. After all, the performance boost will have practically zero benefit in many applications.

 I understand that a user of this library can create their own boxes, as I will. But why should they have to? How does this benefit the kotlin world for every usage of this library to write their own set of wrapper classes? Especially since this library is called "the idiomatic way", I am surprised that it is considered idiomatic to have unboxed atomics with very complicated restrictions even in cases where performance doesn't matter.

**Comment by recursive-rat4** [comment]
Atomicfu has two components: library and plugin. Library provides boxed types, and the plugin rewrites code. You could try to add dependency on library, but skip the plugin.

**Comment by fzhinkin** [comment]
@mgroth0 thank you for elaborating!
Speaking of your particular case with counters, I believe the "arrays of atomic values" feature may cover your needs: https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#arrays-of-atomic-values:
```
import kotlinx.atomicfu.AtomicIntArray

class MyObjectNowMultiplatform {
    private val counters = AtomicIntArray(10)
    fun next(index: Int): Int = counters[index].getAndIncrement()
}
```


> And now after reading the comment from @recursive-rat4 and taking another look at the readme and the implementation of kotlinx.atomicfu.AtomicInt, I am beginning to understand that kotlinx.atomicfu.AtomicInt is essentially already boxed, but that it is the plugin that un-boxes them and causes users to have these restrictions for the sake of better performance. Am I understanding this correctly?

That's correct.


> I tried doing what @recursive-rat4 suggested, and depended on org.jetbrains.kotlin:atomicfu directly but I am not seeing any classes in there without applying the gradle plugin.

Something like that should indeed do the trick:
```
//build.gradle.kts
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:atomicfu:0.23.2")
            }
        }
   }
}
```
```
// some.source.file.kt
import kotlinx.atomicfu.AtomicInt
import kotlinx.atomicfu.atomic

val x: AtomicInt = atomic(0) 
```
Could you please share your build config to check why classes are not available to you?
