### ISSUE TITLE
::<init>: Unsupported operation on atomic variable

### ISSUE THREAD

**Issue by Junzz0** [Kotlin/kotlinx.atomicfu#461]
```
private val _beanTemperature = atomic(Float.NaN)
override val beanTemperature: Float by _beanTemperature
```

atomicfu will compile incorrectly on the desktop, but it will compile successfully on Android.

**Comment by mvicsokolova** [comment]
Hi! 
If you apply the gradle plugin: 
```
plugins {
     id("org.jetbrains.kotlinx.atomicfu") version "0.25.0"
}
```

And enable compiler plugin transformations by setting this flag in your `gradle.properties`: `kotlinx.atomicfu.enableJvmIrTransformation=true`, this code should be compiled successfully. 

(`org.jetbrains.kotlin.plugin.atomicfu` is not supposed to be applied directly --  using the gradle plugin `org.jetbrains.kotlinx.atomicfu` + JVM IR transformation flag is the correct way).
