### ISSUE TITLE
Maven central publication

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.atomicfu#55]
No atomicfu artifacts published at maven central: the latest published version is [`0.11.12`](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/atomicfu-common). This is important since ktor users is [unable to use ktor](https://github.com/ktorio/ktor/issues/950) without specifying additional repositories.

Also notice that the latest release on github is in draft state

**Comment by elizarov** [comment]
Uploaded `0.21.1` to Maven central
