### ISSUE TITLE
More user-friendly Gradle plugin

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.atomicfu#7]
Current usage of Gradle plugin is quite verbose. As explained in README it takes a lot of steps that you need to copy-paste into your gradle project file:

```
def CLASSES_POST_ATOMICFU = file("$buildDir/classes-post-atomicfu/main")

atomicFU {
    inputFiles = sourceSets.main.output.classesDirs
    outputDir = CLASSES_POST_ATOMICFU
    classPath = sourceSets.main.runtimeClasspath
    variant = "FU" // "VH" to use Java 9 VarHandle, "BOTH" to produce multi-version code
}

atomicFU.dependsOn compileKotlin
testClasses.dependsOn atomicFU
jar.dependsOn atomicFU

jar {
    mainSpec.sourcePaths.clear() // hack to clear existing paths
    from files(CLASSES_POST_ATOMICFU, sourceSets.main.output.resourcesDir)
}
```

While we'd like to continue supporting this syntax with explicit specification of `inputFiles`, `outputDir` and `classPath` for backwards compatibility, we'd like to be able to have a completely new default behavior, so that just doing `apply plugin: 'kotlinx-atomicfu'` does all the magic and configures automatic transformation for all source sets.

**Comment by Prototik** [comment]
Isn't it better to implement it as compiler subplugin? (if it possible with current api of course)

**Comment by Prototik** [comment]
Just looked to compiler api: seems not possible to add *transformation* plugin. It supports only few specialized cases: like annotation processing, adding new classes, refining modifiers, but not direct transforming. Not sure though.
