### ISSUE TITLE
What does the Incubator status means for AtomicFu?

### ISSUE THREAD

**Issue by PLNech** [Kotlin/kotlinx.atomicfu#73]
Hi there, first of all thanks for this library!

However I'm confused by its current status. The readme shows this project as `Incubator`, which is [defined on jetbrains.com](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub) as `considered experimental, not mature enough, or lacking in some manner or release quality such testing and supporting documentation`.

We are writing an open source library, and worry that we shouldn't use AtomicFu in our libraries, because of the uncertainty around its maturity and safety in production. But I know that `kotlin.coroutines` relies on AtomicFu, and that coroutines are no more considered experimental, having being added to the kotlin stdlib. 
- Does this mean you consider AtomicFu safe for production?
- Could you share the reasons behind marking this project as `Incubator`? Is it just because of an incomplete `supporting documentation`, or is there another reason?

**Comment by elizarov** [comment]
It means that we are not currently committed to support AtomicFu's usage in other projects. We do support it for its use in our own projects (like `kotlinx.coroutines`), but we don't have resources to support somebody else's use-cases at the moment. It is not just an abstract statement. AtomicFu is indeed quite limited in the number of constructs that it can be safely used with and in its quality (test coverage, easiness to understand its diagnostic messages, etc).

**Comment by PLNech** [comment]
Hi @elizarov, thank you for your reply (and sorry for the slow follow-up)!
We'll take this into account for our libraries.
