### ISSUE TITLE
Support atomic arrays

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.atomicfu#8]
Support `AtomicArray<T>` class. It should be conceptually similar to `Array<AtomicRef<T>>`. The following snippet provides a glimpse of proposed API:

```
val a = AtomicArray<T>(size) // similar to Array constructor

val x = a[i].value // read value
a[i].value = x // set value
a[i].compareAndSet(expect, update) // do atomic operations
```

In `FU` mode it should simply map onto `AtomicReferenceArray` and its operations, but in `VH` mode it shall be efficiently implement via a simple array reference with `VarHandle` to perform atomic operations on elements.

In addition to `AtomicArray`, support for `AtomicBooleanArray`, `AtomicIntArray`, and `AtomicLongArray` shall be provided as well.

**Comment by qwwdfsad** [comment]
>In FU mode it should simply map onto `AtomicReferenceArray`

Shouldn't we consider plain array + unsafe as default?
If for some reason unsafe is unavailable, we can provide opt-out version with `AtomicReferenceArray`

**Comment by elizarov** [comment]
Using unsafe requires a lot of code for all that runtime auto-detection and, since AtomicFU is supposed to be compile-only library, that code is quite cumbersome to carry around. The plan is to generate both `VH` and `FU` code versions by default (see #10) which would alleviate the need to do any runtime checks and would give efficient VarHandle-based implementation for code running on JDK 9+.
