### ISSUE TITLE
SynchronizedObject

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.atomicfu#80]
We need common `SynchronizedObject` with the following common API:

```
public expect open class SynchronizedObject()
public expect inline fun <T> synchronized(lock: SynchronizedObject, block: () -> T): T
```

On both JVM and JS this `SynchronizedObject` typealises to `Any`. On JVM `synchronized` maps to JVM `synchronized`, while on `JS` it simply calls `block()`.

On native it need to be implemented carefully, so that it reused a pool of pthread mutexes for heavy-weight synchronization in a way that requires no resource management for uses of `SynchronizedObject`.

Note, that on Native this primitive will by thread-safe only if all the fields that are protected by `SynchronizedObject` are also `atomic`. This limitation will be further addressed by a separate issue.

**Comment by JakeWharton** [comment]
Typealiases to `Unit` or `Any` on JVM/JS?

**Comment by elizarov** [comment]
> Typealiases to `Unit` or `Any` on JVM/JS?

`Any`, thanks.
