### ISSUE TITLE
Is there the possibility to favour writers?

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx.atomicfu#97]
I have a classic consumer-producer problem with many read and few, but crucial, writes.

What fairness policies does this library uses? Can you tweak them? 

My usecase is an `MutableMap` used as cache. Recovering stuff from server is expensive so I'd like to minimize it as much as possible. 
Of course if there is a write pending, I want no new reads to happens because I may save some from calling the server!

**Comment by elizarov** [comment]
This library just wraps underlying platform abstractions (`AtomicXxxFu` classes on JVM) and does not give any extra guarantees beyond those.
